theme: jekyll-theme-minimal
title: BitcoinTrade (brazilian exchange) SDK .NET
description: The BitcoinTrade API client wrapper for .NET projects.
logo: https://raw.githubusercontent.com/guibranco/bitcointrade-sdk-dotnet/master/logo.png
show_downloads: true
